name       : steamtinkerlaunch
version    : '7.0'
release    : 2
source     :
    - https://github.com/frostworx/steamtinkerlaunch/archive/refs/tags/v7.0.tar.gz : bbaeb6bedd36c3ea7c1f7163230e55ba1bf0eac6427fd3a1773095a9ded7a0a0
license    : GPL-3.0-or-later
component  : games
summary    : Wrapper tool for the Steam client
description: |
    Steam Tinker Launch (short stl) is a Linux wrapper tool for the Steam client which allows customizing and starting tools and options for games quickly on the fly
rundeps    :
    - git
    - xdotool
    - xprop
    - xwininfo
    - yad
setup      : |
    %patch -p1 < $pkgfiles/fix_prefix_substitution.patch
install    : |
    export PREFIX=$installdir/usr
    %make_install
