name       : steamtinkerlaunch
version    : '11.11'
release    : 9
source     :
    - https://github.com/frostworx/steamtinkerlaunch/archive/refs/tags/v11.11.tar.gz : 1e7f9d52753ff9203ddcd69461e6160530dba03747ecfb2a15d7e5dd435d34c4
license    : GPL-3.0-or-later
component  : games
summary    : Wrapper tool for the Steam client
description: |
    Steam Tinker Launch (short stl) is a Linux wrapper tool for the Steam client which allows customizing and starting tools and options for games quickly on the fly
rundeps    :
    - git
    - innoextract
    - vim
    - xdotool
    - xprop
    - xwininfo
    - yad
setup      : |
    %patch -p1 < $pkgfiles/fix_prefix_substitution.patch
install    : |
    export PREFIX=$installdir/usr
    %make_install
    # create symlink for compability with older setups
    ln -s /usr/bin/steamtinkerlaunch $installdir/usr/bin/stl
