name       : steamtinkerlaunch
version    : '12.12'
release    : 11
source     :
    - https://github.com/sonic2kk/steamtinkerlaunch/archive/refs/tags/v12.12.tar.gz : b81b9fc1fe7b87ccd9f62b074ea1e09ce245b42c13b7e009e832272459e3a555
license    : GPL-3.0-or-later
component  : games
summary    : Wrapper tool for the Steam client
description: |
    Steam Tinker Launch (short stl) is a Linux wrapper tool for the Steam client which allows customizing and starting tools and options for games quickly on the fly
rundeps    :
    - git
    - innoextract
    - vim
    - xdotool
    - xprop
    - xwininfo
    - yad
setup      : |
    %patch -p1 < $pkgfiles/fix_prefix_substitution.patch
install    : |
    export PREFIX=$installdir/usr
    %make_install
    # create symlink for compability with older setups
    ln -s /usr/bin/steamtinkerlaunch $installdir/usr/bin/stl
