name       : steamtinkerlaunch
version    : '10.0'
release    : 7
source     :
    - https://github.com/frostworx/steamtinkerlaunch/archive/refs/tags/v10.0.tar.gz : 9337bf239a00c7fe1ccc53b33311391f8bb47b1865d8bbff8b964ade557537b4
license    : GPL-3.0-or-later
component  : games
summary    : Wrapper tool for the Steam client
description: |
    Steam Tinker Launch (short stl) is a Linux wrapper tool for the Steam client which allows customizing and starting tools and options for games quickly on the fly
rundeps    :
    - git
    - innoextract
    - vim
    - xdotool
    - xprop
    - xwininfo
    - yad
setup      : |
    %patch -p1 < $pkgfiles/fix_prefix_substitution.patch
install    : |
    export PREFIX=$installdir/usr
    %make_install
    # create symlink for compability with older setups
    ln -s /usr/bin/steamtinkerlaunch $installdir/usr/bin/stl
