name       : steamtinkerlaunch
version    : 6.15
release    : 1
source     :
    - https://github.com/frostworx/steamtinkerlaunch/archive/refs/tags/v6.15.tar.gz : d912b17457646133e62d43695c6ba01ed9234879895f2b2781842ec476fb63da
license    : GPL-3.0-or-later
component  : games
summary    : Wrapper tool for the Steam client
description: |
    Steam Tinker Launch (short stl) is a Linux wrapper tool for the Steam client which allows customizing and starting tools and options for games quickly on the fly
rundeps    :
    - git
    - xdotool
    - xprop
    - xwininfo
    - yad
install    : |
    export PREFIX=$installdir/usr/
    %make_install
