name       : steamtinkerlaunch
version    : '11.0'
release    : 8
source     :
    - https://github.com/frostworx/steamtinkerlaunch/archive/refs/tags/v11.0.tar.gz : 4a178cce658c51f6b4b77cd0d078485bcf6793db0ff7393b3c6ec35e14762e87
license    : GPL-3.0-or-later
component  : games
summary    : Wrapper tool for the Steam client
description: |
    Steam Tinker Launch (short stl) is a Linux wrapper tool for the Steam client which allows customizing and starting tools and options for games quickly on the fly
rundeps    :
    - git
    - innoextract
    - vim
    - xdotool
    - xprop
    - xwininfo
    - yad
setup      : |
    %patch -p1 < $pkgfiles/fix_prefix_substitution.patch
install    : |
    export PREFIX=$installdir/usr
    %make_install
    # create symlink for compability with older setups
    ln -s /usr/bin/steamtinkerlaunch $installdir/usr/bin/stl
