name       : steamtinkerlaunch
version    : '8.0'
release    : 3
source     :
    - https://github.com/frostworx/steamtinkerlaunch/archive/refs/tags/v8.0.tar.gz : b9adb81fc747f64415820d578c361f3901deec905d559639f2106e53c4f31929
license    : GPL-3.0-or-later
component  : games
summary    : Wrapper tool for the Steam client
description: |
    Steam Tinker Launch (short stl) is a Linux wrapper tool for the Steam client which allows customizing and starting tools and options for games quickly on the fly
rundeps    :
    - git
    - innoextract
    - xdotool
    - xprop
    - xwininfo
    - yad
setup      : |
    %patch -p1 < $pkgfiles/fix_prefix_substitution.patch
install    : |
    export PREFIX=$installdir/usr
    %make_install
    # create symlink for compability with older setups
    ln -s /usr/bin/steamtinkerlaunch $installdir/usr/bin/stl
