name       : steamtinkerlaunch
version    : 9.0.1
release    : 5
source     :
    - https://github.com/frostworx/steamtinkerlaunch/archive/refs/tags/v9.0.1.tar.gz : 0f2d91f78b3414cfdd2b5f1c0c9ccb8786ef039b35f928fcd83d4e6f88f53b32
license    : GPL-3.0-or-later
component  : games
summary    : Wrapper tool for the Steam client
description: |
    Steam Tinker Launch (short stl) is a Linux wrapper tool for the Steam client which allows customizing and starting tools and options for games quickly on the fly
rundeps    :
    - git
    - innoextract
    - vim
    - xdotool
    - xprop
    - xwininfo
    - yad
setup      : |
    %patch -p1 < $pkgfiles/fix_prefix_substitution.patch
install    : |
    export PREFIX=$installdir/usr
    %make_install
    # create symlink for compability with older setups
    ln -s /usr/bin/steamtinkerlaunch $installdir/usr/bin/stl
